http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  user:
    host: localhost
    paths: ['/user','/user/*']
  skill:
    host: localhost
    paths: ['/skills','/skills/*']
  application:
    host: localhost
    paths: ['/application','/application/*']
  opportunity:
    host: localhost
    paths: ['/opportunity','/opportunity/*']
  notification:
    host: localhost
    paths: ['/notification','/notification/*']
  
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  applicationService:
    url: 'http://localhost:4000'
  notificationService:
    url: 'http://localhost:5000'
  opportunityService:
    url: 'http://localhost:6000'
  skillService:
    url: 'http://localhost:7000'
  userService:
    url: 'http://localhost:8000'

    
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
      # - cors:
      #     - action:
      #         origin: ["*"]
      #         methods: GET,POST,PUT,DELETE,OPTIONS
      #         preflightContinue: true
      #         optionsSuccessStatus: 200
      #         credentials: true
      #         maxAge: 600
      #         allowedHeaders:
      #           - Authorization
      #         exposedHeaders:
      #           - Authorization
      # - key-auth:
      #     - action:
      #         apiKeyHeader: Authorization
      #         disableHeadersScheme: false
      #     - condition:
      #         name: not
      #         condition:
      #           name: method
      #           methods:
      #             - OPTIONS

      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
  applicationPipeline:
    apiEndpoints:
      - application
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: applicationService
              changeOrigin: true
  notificationPipeline:
    apiEndpoints:
      - notification
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: notificationService
              changeOrigin: true
  opportunityPipeline:
    apiEndpoints:
      - opportunity
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: opportunityService
              changeOrigin: true
  skillPipeline:
    apiEndpoints:
      - skill
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: skillService
              changeOrigin: true
  userPipeline:
    apiEndpoints:
      - user
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: userService
              changeOrigin: true
